### ISSUE TITLE
Feature request: --exclude parameter

### ISSUE THREAD

**Issue by osa1** [elaforge/fast-tags#17]
It'd be super useful in cases like when we have Haskell files at the top level(so we want to run `fast-tags . -R`) but we don't want to tag `.cabal-sandbox` etc.

**Comment by elaforge** [comment]
How about fast-tags **/*.hs?  Or fast-tags $(find . -name '*.hs')?  Personally all my projects have an 'all_hs' script that prints all the source files according to various criteria (test, main, etc.).

**Comment by ntc2** [comment]
Another vote for this `--exclude` feature. Projectile mode in Emacs passes `--exclude`s to the `TAGS` generator. Projectile lets you configure what program is used to generate the `TAGS` file, but assumes that it supports `--exclude` and that it does recursive generation. E.g. in my project Projectile passed
```
--exclude=.idea --exclude=.ensime_cache --exclude=.eunit --exclude=.git --exclude=.hg --exclude=.fslckout --exclude=_FOSSIL_ --exclude=.bzr --exclude=_darcs --exclude=.tox --exclude=.svn --exclude=.stack-work
```
to the `TAGS` generator.

**Comment by elaforge** [comment]
Ok, it's not hard to add, so why not.  Neither ctags nor hasktags has it, so I'm not sure what is the standard interpretation.  Exclude only exact matches in the given directory?  Exact matches in all directories?

The argument against is that `find ... | fast-tags -` will always be more powerful and general, but in practice I'm starting to find -R pretty convenient too, so why not --exclude too.

**Comment by ntc2** [comment]
> Ok, it's not hard to add, so why not. Neither ctags nor hasktags has it, so I'm not sure what is the standard interpretation. Exclude only exact matches in the given directory? Exact matches in all directories?

It appears to come from exuberant-ctags, which is the version of ctags that Projectile recommends. Here is a description of the exuberant-ctags options: http://ctags.sourceforge.net/ctags.html#OPTIONS

**Comment by elaforge** [comment]
Seems to work.  Give it a try.

**Comment by ntc2** [comment]
@elaforge Thanks, tested it and works for me! In the mean time I ended up just tweaking `haskell-mode` to do the TAGS excludes, and now I'm using `haskell-mode` instead of `projectile` for my TAGS generation: https://github.com/haskell/haskell-mode/pull/1603/files .
