### ISSUE TITLE
Doesn't recognize pattern synonyms

### ISSUE THREAD

**Issue by ekmett** [elaforge/fast-tags#31]
It'd be fairly quick to add pattern synonym support

```
pattern Foo ::
```

**Comment by sergv** [comment]
Can you provide a complete example where `fast-tags` fails? Latest version should detect pattern synonyms and the tests are green https://github.com/elaforge/fast-tags/blob/master/tests/MainTest.hs#L856-L886.

**Comment by elaforge** [comment]
I just tried this for the various kinds of patterns from the ghc manual, and put them all in tags:

```
pattern Arrow t1 t2 = App "->"    [t1, t2]

pattern Head x <- x:xs

pattern HeadC x <- x:xs where
  HeadC x = [x]

pattern Point :: Int -> Int -> (Int, Int)
pattern Point{x, y} = (x, y)
```

produces

```
Arrow	T.hs	3;"	p
Head	T.hs	5;"	p
HeadC	T.hs	7;"	p
Point	T.hs	10;"	p
```
