### ISSUE TITLE
Way to avoid stdin for no arguments

### ISSUE THREAD

**Issue by ekmett** [elaforge/fast-tags#32]
It would be nice to have an option to not read from stdin if no arguments are received.

(I can do this in the shell, by building a wrapper but it is rather heavy weight.)

Then init-tags could call with that options so that running init-tags with no arguments wouldn't either build everything or grab stdin depending on the presence or absence of the tags file.

Also `init-tags` should probably process the named argument even if it finds all the haskell files, just in case the file being edited isn't under the current tree, or has a funny extension.

**Comment by elaforge** [comment]
I don't use the "filenames from stdin" feature myself, but in retrospect I think it should go the other way around, so have a --filenames-on-stdin or something.  It would be an easy change but I don't want to gratuitously break someone's scripts.  It looks like it was added by @sergv in 189434eaf3324b79ea9fb2a1b0bb732ccde2dea3 so I'll try to get input from him.  I don't understand github too well... will adding the @ cc him?

On the second part, I guess what you're saying is that init-tags ignores the files you gave it if 'tags' exists, and shouldn't?  Yeah, I agree with that, I'll fix that.

**Comment by elaforge** [comment]
6c2eece62c2ae3e44391a4bad0a3118b471676cb should fix the second part.

**Comment by elaforge** [comment]
I mean 87520fa9c54231bba215a38bf5848a345d4e71a5, I amended the patch to ignore duplicate filenames.

**Comment by elaforge** [comment]
Sorry about the late response, I never got a response and then forgot about it.

This should be fixed by bb93eda667ef76e6be8b86d83db2a26b93cdf717
