### ISSUE TITLE
support multiple source roots

### ISSUE THREAD

**Issue by elaforge** [elaforge/fast-tags#34]
In #33 @JonnyRa says:

The code I'm working on has a repository root with lots of different projects/packages in it so the folder structure is like:

`package-name/src/Namespace/Is/Here.hs`
which is resulting in tags like
`package-name.src.Namespace.Is.Here.functionName`

whereas the namespaces/module names referred to in code will just be the
Namespace.Is.Here part.

From the error message it seems to be correctly making the fully qualified name to query the tags (eg it's querying for Namespace.Is.Here.functionName)

Not sure what a good approach is... could possibly search for the tag as a prefix of generated ones...,. or slightly hacky could recognise src as a package root. I'm not sure if that's a stack thing or just a more general convention...

actually thinking about it, it should be possible to parse the correct names out of each module declaration in the files?

**Comment by elaforge** [comment]
I think there's no way for vim to know the namespace roots unless you tell it somehow.  I don't know how people handle multiple roots in general, I'd think you'd need multiple tags files and a search path.  In fact it looks like vim's 'tags' option supports just that.  You'd need some special setup though, to keep them up to date.  That would be something like a .vimrc in the root dir that sets 'tags', and a more specialized init-tags that also understands namespace roots.

But now that I think on it, you're right that we could qualify with the complete path, taken from the file name, even though it's no longer a haskell identifier.  But since qualified_tag.tag_word can't tell which package directory an import came from, it would have to try multiple ones, which means it would need the list of package roots.  I think this winds up being much the same as maintaining the 'tags' search path, except we have to implement the searching manually instead of using vim's built-in functionality.  This is making me think the first way is better after all.

@JonnyRa do you want to tackle this one?

**Comment by JonnyRa** [comment]
Sure ok, I'll have a look over those recent changes and see what fully-qualified is up to.

**Comment by JonnyRa** [comment]
I'm actually experiencing the same issues on the fast-tags repo as everything in there is in a src directory aswell (I'm running vim/init-tags from the repository root again).

I feel like SrcPos should have module in there.  

Currently module's names get the namespace removed in Tag/blockTags.  If that didn't happen (or both bits were stored) and then the module tag was pulled out of the list, then when Tag/qualify got called you could use the module name rather than guessing it from the file... perhaps Maybe module could be hung on each of the SrcPos things - it'd be easy to get hold of it in qualify then.  

I'm going to have to leave it at these notes for the time being, might be able to find a bit of time to sort it out next week though.  I also haven't looked at how anything gets tested yet, my worry would be that I might break one of the other options in fixing this one.

**Comment by elaforge** [comment]
Yeah, you solve that by `cd src` and then run tags and vim from there :)

You could get the module by not stripping when you make the Module tag, and then search the tags list for a Module tag.  No need to attach anything to SrcPos, I think you'd wind up doing that as an extra step between generate tags and apply qualification.

Tests are run via `cabal test`, though very slowly as with seemingly everything in cabal.  I'm sure the test framework has a way to quickly rerun tests though.

**Comment by elaforge** [comment]
I think the new `--cabal` flag solves this, at least assuming you have a cabal file indicating each of those package roots.  I'll pre-emptively close this, feel free to reopen if it doesn't actually work for you.

**Comment by JonnyRa** [comment]
Hi!  Sorry I never got around to doing anything about this.  Work has been made busy so we've not had time to do much mucking around with tools.  

I'll give it a go, do I just add `--cabal` and also `--fully-qualified` and then enable that fully qualified snippet of python? I can't remember the details of the latter - I just reverted to using the unqualified tags and using fzf along with a cword search when I needed to disambiguate.

**Comment by JonnyRa** [comment]
Also don't know if I mentioned it before but I made a little thing for generating imports (for your own code, not standard library) that hangs off the back of having tags available.  It's very simple but also very useful if you're in a large or unfamiliar project https://github.com/JonnyRa/vim-himposter

**Comment by elaforge** [comment]
I think it should coexist with --fully-qualified, but I might have not used both together yet.  I should try it because the ambiguous tags are especially annoying when there are more of them.

Interesting about the imports generator.  I've long used `fix-imports`, which has a different strategy, it uses qualification and per-project module priorities to guess what module you need, with explicit configuration for unqualified imports.  This fits better with my usual style, which is to use unqualified imports only for a small unchanging set of functions.  I didn't think of using tags, maybe because I did `fix-imports` before `fast-tags`, but it makes me think I could use the tags to further disambiguate and maybe get rid of module priorities entirely.  I.e. if I see `M.f` I can eliminate all the `M`s that don't export `f`.  Thanks for the idea, and I'll probably look at `vim-himposter` too!

**Comment by JonnyRa** [comment]
Cool cheers, I'll give it a go.  Is `fix-imports` a program or a flag for something?  Maybe I've reinvented the wheel

**Comment by elaforge** [comment]
It's a separate program, should be findable on hackage or my github.  It's a standalone program.  This wheel has been invented a lot, and this one is specialized to my usage, so it may not fit with your habits.  Worth a try though!
