### ISSUE TITLE
incorrect emacs tag format

### ISSUE THREAD

**Issue by fommil** [elaforge/fast-tags#42]
in

https://github.com/elaforge/fast-tags/blob/master/src/FastTags/Emacs.hs#L40

```
, showt (linenum-1) <> "," <> showt linenum
```

but I think this is supposed to be the line and then the byte offset, c.f. https://stackoverflow.com/questions/1990579

In addition, the `Token.posPrefix pos` is more typically the entire line as it is shown in the preview mode.

**Comment by fommil** [comment]
I had a quick look to see if I could add this support, but `mkSrcPos` takes input from alex and that seems like a rabbit hole... I'll close as "too hard".

**Comment by fommil** [comment]
I applied this diff but my searches still aren't working so I'm investigating if the problem is elsewhere...

```diff
modified   src/FastTags/Emacs.hs
@@ -37,10 +37,11 @@ formatTag :: Token.Pos Tag.TagVal -> Text
 formatTag (Token.Pos pos tag) = Text.concat
     [ Token.posPrefix pos, "\x7f"
     , Tag.tvName tag, "\x01"
-    , showt (linenum-1) <> "," <> showt linenum
+    , showt linenum <> "," <> showt offset
     ]
     where
     linenum = Token.unLine (Token.posLine pos)
+    offset = Token.unOffset (Token.posOffset pos)
 
 showt :: Show a => a -> Text
 showt = Text.pack . show
modified   src/FastTags/LexerTypes.hs
@@ -77,8 +77,12 @@ mkAlexInput s trackPrefixes = AlexInput
     utf8BOM' = "\xFEFF"
 
 mkSrcPos :: FilePath -> AlexInput -> SrcPos
-mkSrcPos filename (AlexInput {aiLine, aiPrefix}) =
-    SrcPos { posFile = filename, posLine = aiLine, posPrefix = aiPrefix }
+mkSrcPos filename (AlexInput {aiLine, aiPrefix, aiAbsPos}) =
+    SrcPos { posFile = filename
+           , posLine = aiLine
+           , posOffset = Offset aiAbsPos
+           , posPrefix = aiPrefix
+           }
 
 -- TODO: Not very efficient to snoc every character here, figure out something
 -- better.
modified   src/FastTags/Token.hs
@@ -21,22 +21,26 @@ instance Show a => Show (Pos a) where
 newtype Line = Line { unLine :: Int }
     deriving (Show, Eq, Ord, NFData, Num)
 
+newtype Offset = Offset { unOffset :: Int }
+    deriving (Show, Eq, Ord, NFData, Num)
+
 increaseLine :: Line -> Line
 increaseLine (Line n) = Line $! n + 1
 
 data SrcPos = SrcPos {
     posFile     :: !FilePath
     , posLine   :: {-# UNPACK #-} !Line
+    , posOffset :: {-# UNPACK #-} !Offset
     -- | No need to keep prefix strict since most of the prefixes will not be
     -- used.
     , posPrefix :: Text
     } deriving (Eq, Ord)
 
 instance NFData SrcPos where
-    rnf (SrcPos x y z) = rnf x `seq` rnf y `seq` rnf z
+    rnf (SrcPos w x y z) = rnf w `seq` rnf x `seq` rnf y `seq` rnf z
 
 instance Show SrcPos where
-    show (SrcPos fn line prefix) =
+    show (SrcPos fn line _ prefix) =
         fn ++ ":" ++ show (unLine line) ++ prefix'
         where
         prefix' | Text.null prefix = ""
```

**Comment by elaforge** [comment]
Thanks for looking into it.  I don't know how to use emacs so I'm not the best to help debug emacs problems.  @sergv did the alex implementation so he should be able to answer questions about it.

**Comment by fommil** [comment]
oh, I think I see the problem! There are multiple problems. First of all, I think I fixed the line number / offset problem, but the full text string seems to be relevant because Emacs dedupes based on the prefix and that means if there are multiple hits it will only pick the first one. I'll see if I can send a PR with a fix.

**Comment by fommil** [comment]
that theory is incorrect... I tried appending the line number to the prefix string and emacs (`etags-select` to be exact) still isn't showing more than one tag per file of this name. This is very strange.

**Comment by sergv** [comment]
Yes, Emacs requires prefix for producing correct TAGS file. And there's `posPrefix` field in `SrcPos` exactly for that - it contains token's prefix, i.e. text from beginning of line to the start of the token.

**Comment by fommil** [comment]
hi @sergv, I have updated my PR. Emacs needs more than the prefix, it needs the entire line. I've worked out how to do that, so it's all good :smile: I'm currently updating the unit tests.
