### ISSUE TITLE
Generate paths relative to output file

### ISSUE THREAD

**Issue by pbrisbin** [elaforge/fast-tags#44]
We have a nested tree of Haskell packages such as:

```
haskell/
  common/
    this/
      That.hs
  backend/
    that/
      TheOther.hs
```

To support jumping "across branches" but also having the best local tags in the case of conflicting names, we can generate tags at each level:

```
haskell/
  tags
  common/
    tags
    this/
      tags
      That.hs
  backend/
    tags
    that/
      tags
      TheOther.hs
```

And (e.g.) vim handles this nicely depending on your current working directory. It will look first in `./tags` then if it finds no identifier try `../tags` and so on.

I *thought*, I could do something like this:

```console
fast-tags -R haskell -o haskell/tags
fast-tags -R haskell/common -o haskell/common/tags
fast-tags -R haskell/backend -o haskell/backend/tags
fast-tags -R haskell/common/this -o haskell/common/this/tags
fast-tags -R haskell/backend/that -o haskell/backend/that/tags
```

But the paths come out as relative to the directory in which you invoke `fast-tags`.

For example, `haskell/common/tags` would have:

```
someIdentifier: haskell/common/this/That.hs
```

Which is broken. It needs to be:

```
someIdentifier: this/That.hs
```

Because these are expected to be relative from the directory where the tags file was found.

I *think* this is always true of any valid ctags system, and not just a vim-ism. So I think that means that correct behavior here would always be to generate paths relative to the dirname of `-o`, when given.

As a workaround, we're doing this now:

```console
(cd haskell && fast-tags -R .)
(cd haskell/common && fast-tags -R .)
(cd haskell/backend && fast-tags -R .)
(cd haskell/common/this && fast-tags -R .)
(cd haskell/backend/that && fast-tags -R .)
```

Which is fine, but a bit noisier.

**Comment by elaforge** [comment]
The cd version seems ok to me, effectively that's how you tell it where the tags should be relative from.

That said though, multiple tags files seem like a hassle to keep up to date though, in addition to making vim search multiple files.  Why not put everything in one file and update it incrementally?  There is a new `--cabal` flag which will look for source files relative to hs-source-dirs, I use it at work to keep our subset of hackage indexed in a single tags file.  You could maybe do `fast-tags --cabal **/*.cabal` to initialize from scratch, and then update incrementally on each file modify.

**Comment by pbrisbin** [comment]
> The cd version seems ok to me, effectively that's how you tell it where the tags should be relative from.

OK, thank you for considering. Do think think it's worth documentation or a note somewhere to indicate that using `-o` to produce a file in any other directory will produce a broken file?

**Comment by pbrisbin** [comment]
Sorry for the delayed replies, but...

> multiple tags files seem like a hassle to keep up to date though, in addition to making vim search multiple files. Why not put everything in one file and update it incrementally?

Well, it's not really a hassle since we have whatever incantation is needed hiding behind a simple `make tags` in the project. And the reason why I like multiple files is if there are collisions across the source tree:

Given

```
haskell/
  tags
  foo/
    tags
  bar/
    tags
```

If I'm working on `bar` I will open my editor in `bar/` and so if there is an identifier (say `find`) that exists in `bar/` and `foo/`, a `^]` will use `./tags` first and navigate directly to it. If there's an identifier only in `foo/` it will find it in `../tags` and jump to it.

In practice, I have no idea if this has ever mattered, it's just why I started with this system.

> Do you want to do it or shall I?

I'll let you go ahead, or not. I'm satisfied enough with just having this discussion, so if you feel motivated to extend the help go for it; if not, I don't mind.

> It's not exactly "broken" though, I use that flag to put it in a build directory, and since I run vim in the root, it needs the paths to be relative to the repo root. 

If I understand what you're saying, you:

- Generate the tags file to `build/tags`, with paths relative from `.`
- Open your editor from within `.`
- Have your editor configured to use `build/tags`

So it works because you *also* have step 3 -- is that accurate?

That seems like a reasonable workflow, and sheds some more light for me on the intention of `-o` -- you just have to also be configuring your editor to match.

> Do you think something like "filename paths are always relative to the current directory, so if you want relative to a different directory you should use cd, not -o" would get the point across?

To be honest, after thinking through all this a few times, I probably land on the side of *not* documenting this. I'm now thinking it's more confusing than useful.

Do you happen to know how `ctags -o` works in this regard, and if they document that behavior anywhere? I'd probably just take my cues from them.
