### ISSUE TITLE
Some TemplateHaskell usages are treated as operator declarations

### ISSUE THREAD

**Issue by d86leader** [elaforge/fast-tags#54]
My current codebase is sprinkled with usages of template haskell like this:

    {-# LANGAUGE TemplateHaskell -#}
    module Example where
    
    import Local.TH
    concat <$> sequence [thFunc1, thFunc2]

When I run fast-tags on a file like this, it generates tags for `<$>`. I expect it not to generate tags for an operator like this, because there isn't even an `=` sign here.

**Comment by sergv** [comment]
@d86leader I tried running fast tags from latest master commit on your example but it didn't produce any tags
```
$ cat Test.hs 

{-# LANGAUGE TemplateHaskell -#}

module Test where

import Local.TH

concat <$> sequence [thFunc1, thFunc2]

$ fast-tags -R . -o- -v
0: Test.hs                                                                    
!_TAG_FILE_SORTED	1	//
```

Could you please provide example where you experience the problem.

**Comment by d86leader** [comment]
No problem, here is my example and how I run it:
```
~/Projects/temp> rm tags
~/Projects/temp> cat Example.hs
{-# LANGUAGE TemplateHaskell #-}
module Example where
concat <$> sequence
  []
concat <*> sequence []
~/Projects/temp> fast-tags Example.hs
~/Projects/temp> cat tags
!_TAG_FILE_SORTED	1	//
<$>	Example.hs	3;"	o
<*>	Example.hs	5;"	o
Example	Example.hs	2;"	m
~/Projects/temp> fast-tags --version
fast-tags, version 2.0.0
```
Fast-tags are installed from `nixpkgs-21.11pre325387.f112b512e17`

**Comment by d86leader** [comment]
Also your example generates nothing because it has a typo in the pragma closing symbols, so it treats the whole file as a comment. (= If I try to fix it, the tags for operators are generated.
