### ISSUE TITLE
Test-suite failure on nixpkgs with ghc 9.0.2

### ISSUE THREAD

**Issue by lf-** [elaforge/fast-tags#61]
Logs:
https://gist.github.com/35b120d0d25b7272adc86feb654428e2

Repro with:
`nix-build --check -E '(import (builtins.fetchTarball "https://github.com/nixos/nixpkgs/archive/cbe587c735b734405f56803e267820ee1559e6c1.tar.gz") { config.allowBroken = true; }).haskell.packages.ghc902.fast-tags'`

**Comment by sergv** [comment]
I think I've fixed it in https://github.com/elaforge/fast-tags/pull/60. @lf- can you try out with the version from master to confirm that it's fixed? Then we can ping @elaforge to make a release.

**Comment by lf-** [comment]
I believe it is fixed, since someone put the patch in-tree in nixpkgs and turned the tests back on 👍🏻

**Comment by sergv** [comment]
@elaforge Polite ping to either make a release or discuss getting backup maintainer able to upload on Hackage.

**Comment by elaforge** [comment]
Hey there, sorry about the delay.  Version updated to 2.0.2 and uploaded to hackage: https://hackage.haskell.org/package/fast-tags-2.0.2

As for backup hackager, I'd be happy to add you as an uploader, @sergv what's your hackage username?

**Comment by sergv** [comment]
@elaforge thanks, my hackage id is `SergeyVinokurov`.

**Comment by elaforge** [comment]
Added!
