### ISSUE TITLE
Instructions on how to integrate with vim?

### ISSUE THREAD

**Issue by AKurilin** [elaforge/fast-tags#8]
I've been looking around for a tags generator to work nicely with vim's tagbar and it looks like fast-tags is one of the only recently maintained project out there for Haskell.

I'm wondering if you could add instructions on how to correctly user fast-tags. I installed it from cabal, I have the binary on my path, but using `au BufWritePost *.hs silent !init-tags %` from the .vimrc doesn't actually do anything.

I'm guessing that line was meant to be `au BufWritePost *.hs silent !init-tags %`, but that actually makes my vim buffer go blank. Not sure what to do there. Advice?

Edit: I actually figured out that I need to add that init-tags script from this repo to the path. Still no luck with vim integration.

**Comment by elaforge** [comment]
I use

    au BufWritePost *.hs            silent !tools/init_tags %

It works for me.  You could try running the ! shell out at the ex prompt, run the script by hand, etc.  Other than that, it looks like a vim debugging job, not really related to fast-tags.

**Comment by AKurilin** [comment]
Yep looks like it's working as intended, sorry for the confusion :)
